insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('abk', 'ab', 'Abkhaz', 'Аҧсуа');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ace', NULL, 'Achinese', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ach', NULL, 'Acoli', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ada', NULL, 'Adangme', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ady', NULL, 'Adyghe; Adygei', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('aar', 'aa', 'Afar', 'Afaraf');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('afh', NULL, 'Afrihili', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('afr', 'af', 'Afrikaans', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('afa', NULL, 'Afro-Asiatic', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ain', NULL, 'Ainu', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('aka', 'ak', 'Akan', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('akk', NULL, 'Akkadian', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('alb', 'sq', 'Albanian', 'Shqip');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ale', NULL, 'Aleut', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('alg', NULL, 'Algonquian languages', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('tut', NULL, 'Altaic', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('amh', 'am', 'Amharic', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('apa', NULL, 'Apache languages', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ara', 'ar', 'Arabic', 'العربية');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('arg', 'an', 'Aragonese', 'Aragonés');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('arc', NULL, 'Aramaic', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('arp', NULL, 'Arapaho', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('arn', NULL, 'Araucanian', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('arw', NULL, 'Arawak', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('arm', 'hy', 'Armenian', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('rup', NULL, 'Aromanian', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('art', NULL, 'Artificial', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('asm', 'as', 'Assamese', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ast', NULL, 'Asturian; Bable', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ath', NULL, 'Athapascan languages', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('aus', NULL, 'Australian languages', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('map', NULL, 'Austronesian', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ava', 'av', 'Avaric', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ave', 'ae', 'Avestan', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('awa', NULL, 'Awadhi', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('aym', 'ay', 'Aymara', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('aze', 'az', 'Azerbaijani', 'Azərbaycanca');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ban', NULL, 'Balinese', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('bat', NULL, 'Baltic', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('bal', NULL, 'Baluchi', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('bam', 'bm', 'Bambara', 'Bamanankan');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('bai', NULL, 'Bamileke languages', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('bad', NULL, 'Banda', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('bnt', NULL, 'Bantu', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('bas', NULL, 'Basa', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('bak', 'ba', 'Bashkir', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('baq', 'eu', 'Basque', 'Euskera');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('btk', NULL, 'Batak (Indonesia)', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('bej', NULL, 'Beja', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('bel', 'be', 'Belarusian', 'Беларуская мова');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('bem', NULL, 'Bemba', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ben', 'bn', 'Bangla', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ber', NULL, 'Berber', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('bho', NULL, 'Bhojpuri', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('bih', 'bh', 'Bihari', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('bik', NULL, 'Bikol', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('bin', NULL, 'Bini', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('bis', 'bi', 'Bislama', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('byn', NULL, 'Blin; Bilin', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('bos', 'bs', 'Bosnian', 'Bosanski');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('bra', NULL, 'Brazilian Portuguese', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('bre', 'br', 'Breton', 'Brezhoneg');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('bug', NULL, 'Buginese', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('bul', 'bg', 'Bulgarian', 'Български');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('bua', NULL, 'Buriat', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('bpm', NULL, 'Bishnupriya Manipuri(Imarthar)', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('bur', 'my', 'Burmese', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('cad', NULL, 'Caddo', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('car', NULL, 'Carib', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('cat', 'ca', 'Catalan', 'català');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('cau', NULL, 'Caucasian', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ceb', NULL, 'Cebuano', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('cel', NULL, 'Celtic', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('cai', NULL, 'Central American Indian', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('chg', NULL, 'Chagatai', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('cmc', NULL, 'Chamic languages', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('cha', 'ch', 'Chamorro', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('che', 'ce', 'Chechen', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('chr', NULL, 'Cherokee', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('chy', NULL, 'Cheyenne', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('chb', NULL, 'Chibcha', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('nya', 'ny', 'Chichewa; Chewa; Nyanja', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('chi', 'zh', 'Chinese', '中文');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('chn', NULL, 'Chinook jargon', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('chp', NULL, 'Dene Suline', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('cho', NULL, 'Choctaw', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('chu', 'cu', 'Church Slavonic', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('chk', NULL, 'Chuukese', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('chv', 'cv', 'Chuvash', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('nwc', NULL, 'Classical Newari', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('cop', NULL, 'Coptic', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('cor', 'kw', 'Cornish', 'Kernewek');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('cos', 'co', 'Corsican', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('cre', 'cr', 'Cree', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('mus', NULL, 'Creek; Muskogean', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('crp', NULL, 'Creoles and Pidgins', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('cpe', NULL, 'Creoles and Pidgins, English-based', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('cpf', NULL, 'Creoles and Pidgins, French-based', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('cpp', NULL, 'Creoles and Pidgins, Portuguese-based', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('crh', NULL, 'Crimean Tatar; Crimean Turkish', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('scr', 'hr', 'Croatian', 'Hrvatski');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('cus', NULL, 'Cushitic', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('cze', 'cs', 'Czech', 'Čeština');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('dak', NULL, 'Dakota', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('dan', 'da', 'Danish', 'Dansk');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('dar', NULL, 'Dargwa', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('day', NULL, 'Dayak', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('del', NULL, 'Delaware', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('din', NULL, 'Dinka', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('div', 'dv', 'Divehi', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('doi', NULL, 'Dogri', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('dgr', NULL, 'Dogrib', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('dra', NULL, 'Dravidian', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('dua', NULL, 'Duala', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('dut', 'nl', 'Dutch; Flemish', 'Nederlands');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('dum', NULL, 'Dutch, Middle (ca. 1050–1350)', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('dyu', NULL, 'Dyula', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('dzo', 'dz', 'Dzongkha', 'རྫོང་ཁ');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('efi', NULL, 'Efik', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('egy', NULL, 'Egyptian (Ancient)', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('eka', NULL, 'Ekajuk', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('elx', NULL, 'Elamite', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('eng', 'en', 'English', 'English');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('enm', NULL, 'English, Middle (ca. 1100–1500)', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ang', NULL, 'English, Old (ca. 450–1100)', 'Englisc');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('myv', NULL, 'Erzya', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('epo', 'eo', 'Esperanto', 'Esperanto');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('est', 'et', 'Estonian', 'Eesti keel');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ewe', 'ee', 'Ewe', 'Ɛʋɛgbɛ');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ewo', NULL, 'Ewondo', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('fan', NULL, 'Fang', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('fat', NULL, 'Fanti', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('fao', 'fo', 'Faroese', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('fij', 'fj', 'Fijian', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('fil', NULL, 'Filipino', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('fin', 'fi', 'Finnish', 'suomi');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('fiu', NULL, 'Finno-Ugrian', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('fon', NULL, 'Fon', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('fre', 'fr', 'French', 'français');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('fry', 'fy', 'Frisian', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('fur', NULL, 'Friulian', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ful', 'ff', 'Fulah', 'Fulfulde, Pulaar, Pular');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('gaa', NULL, 'Ga', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('glg', 'gl', 'Galician', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('lug', 'lg', 'Ganda', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('gay', NULL, 'Gayo', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('gba', NULL, 'Gbaya', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('gez', NULL, 'Geez', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('geo', 'ka', 'Georgian', 'Kartuli');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ger', 'de', 'German', 'Deutsch');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('nds', NULL, 'German, Low; Low German; Saxon, Low; Low Saxon', 'Nederdüütsch, Plattdüütsch');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('gem', NULL, 'Germanic', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('gil', NULL, 'Gilbertese; Kiribati', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('gon', NULL, 'Gondi', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('gor', NULL, 'Gorontalo', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('got', NULL, 'Gothic', 'Gutisk');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('grb', NULL, 'Grebo', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('gre', 'el', 'Greek', 'Ελληνικά');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('kal', 'kl', 'Greenlandic; Kalaallisut', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('grn', 'gn', 'Guarani', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('guj', 'gu', 'Gujarati', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('gwi', NULL, 'Gwich''in', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('hai', NULL, 'Haida', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('hat', 'ht', 'Haitian Creole; Haitian', 'Kreyòl ayisyen');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('hau', 'ha', 'Hausa', 'هَوُسَ');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('haw', NULL, 'Hawaiian', '''Ōlelo Hawai''i');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('heb', 'he', 'Hebrew', 'עברית');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('her', 'hz', 'Herero', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('hil', NULL, 'Hiligaynon', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('him', NULL, 'Himachali', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('hin', 'hi', 'Hindi', 'हिन्दी');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('hmo', 'ho', 'Hiri Motu', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('hit', NULL, 'Hittite', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('hmn', NULL, 'Hmong', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('hun', 'hu', 'Hungarian', 'Magyar');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('hup', NULL, 'Hupa', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('iba', NULL, 'Iban', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ice', 'is', 'Icelandic', 'íslenska');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ido', 'io', 'Ido', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ibo', 'ig', 'Igbo', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ijo', NULL, 'Ijo', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ilo', NULL, 'Iloko', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('smn', NULL, 'Inari Sami', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('inc', NULL, 'Indic', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ine', NULL, 'Indo-European', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ind', 'id', 'Indonesian', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('inh', NULL, 'Ingush', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ina', 'ia', 'Interlingua (International Auxiliary Language Association)', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ile', 'ie', 'Interlingue', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('iku', 'iu', 'Inuktitut', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ipk', 'ik', 'Inupiaq', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ira', NULL, 'Iranian', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('gle', 'ga', 'Irish', 'Gaeilge');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('iro', NULL, 'Iroquoian languages', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ita', 'it', 'Italian', 'Italiano');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('jpn', 'ja', 'Japanese', '日本語');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('jav', 'jv', 'Javanese', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('jbo', NULL, 'Lojban', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('jrb', NULL, 'Judeo-Arabic', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('jpr', NULL, 'Judeo-Persian', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('kbd', NULL, 'Kabardian', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('kab', NULL, 'Kabyle', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('kac', NULL, 'Kachin', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('xal', NULL, 'Kalmyk; Oirat', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('kam', NULL, 'Kamba', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('kan', 'kn', 'Kannada', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('kau', 'kr', 'Kanuri', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('krc', NULL, 'Karachay-Balkar', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('kaa', NULL, 'Kara-Kalpak', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('kar', NULL, 'Karen', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('kas', 'ks', 'Kashmiri', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('csb', NULL, 'Kashubian', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('kaw', NULL, 'Kawi', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('kaz', 'kk', 'Kazakh', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('kha', NULL, 'Khasi', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('khm', 'km', 'Khmer', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('khi', NULL, 'Khoisan', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('kho', NULL, 'Khotanese', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('kik', 'ki', 'Kikuyu; Gikuyu', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('kmb', NULL, 'Kimbundu', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('kin', 'rw', 'Kinyarwanda', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('kir', 'ky', 'Kirghiz', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('kom', 'kv', 'Komi', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('kon', 'kg', 'Kongo', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('kok', NULL, 'Konkani', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('kor', 'ko', 'Korean', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('kos', NULL, 'Kosraean', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('kpe', NULL, 'Kpelle', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('kro', NULL, 'Kru', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('kua', 'kj', 'Kuanyama; Kwanyama', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('kum', NULL, 'Kumyk', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('kur', 'ku', 'Kurdish', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('kru', NULL, 'Kurukh', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('kut', NULL, 'Kutenai', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('krl', NULL, 'Karelian', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('lad', NULL, 'Ladino', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('lah', NULL, 'Lahnda', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('lam', NULL, 'Lamba', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('lao', 'lo', 'Lao', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('lat', 'la', 'Latin', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('lav', 'lv', 'Latvian', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('lez', NULL, 'Lezghian', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('lim', 'li', 'Limburgish; Limburger; Limburgan', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('lin', 'ln', 'Lingala', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('lit', 'lt', 'Lithuanian', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('jbo', NULL, 'Lojban', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('dsb', NULL, 'Lower Sorbian', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('loz', NULL, 'Lozi', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('lub', 'lu', 'Luba-Katanga', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('lua', NULL, 'Luba-Lulua', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('lui', NULL, 'Luiseno', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('smj', NULL, 'Lule Sami', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('lun', NULL, 'Lunda', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('luo', NULL, 'Luo', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('lus', NULL, 'Lushai', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ltz', 'lb', 'Luxembourgish; Letzeburgesch', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('mac', 'mk', 'Macedonian', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('mad', NULL, 'Madurese', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('mag', NULL, 'Magahi', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('mai', NULL, 'Maithili', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('mak', NULL, 'Makasar', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('mlg', 'mg', 'Malagasy', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('may', 'ms', 'Malay', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('mal', 'ml', 'Malayalam', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('mlt', 'mt', 'Maltese', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('mnc', NULL, 'Manchu', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('mdr', NULL, 'Mandar', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('man', NULL, 'Mandingo', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('mni', NULL, 'Manipuri', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('mno', NULL, 'Manobo languages', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('glv', 'gv', 'Manx', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('mao', 'mi', 'Māori', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('mar', 'mr', 'Marathi', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('chm', NULL, 'Mari', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('mah', 'mh', 'Marshallese', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('mwr', NULL, 'Marwari', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('mas', NULL, 'Masai', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('myn', NULL, 'Mayan languages', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('men', NULL, 'Mende', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('mic', NULL, 'Mi''kmaq; Micmac', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('min', NULL, 'Minangkabau', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('mwl', NULL, 'Mirandese', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('moh', NULL, 'Mohawk', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('mdf', NULL, 'Moksha', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('mol', 'mo', 'Moldavian', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('mkh', NULL, 'Mon-Khmer', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('lol', NULL, 'Mongo', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('mon', 'mn', 'Mongolian', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('mos', NULL, 'Mossi', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('mun', NULL, 'Munda languages', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('nah', NULL, 'Nahuatl', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('nau', 'na', 'Nauruan', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('nav', 'nv', 'Navajo; Navaho', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('nde', 'nd', 'Ndebele, North', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('nbl', 'nr', 'Ndebele, South', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ndo', 'ng', 'Ndonga', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('nap', NULL, 'Neapolitan', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('nep', 'ne', 'Nepali', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('new', NULL, 'Newari; Nepal Bhasa', 'Nepal Bhyae');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('nia', NULL, 'Nias', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('nic', NULL, 'Niger-Kordofanian', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ssa', NULL, 'Nilo-Saharan', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('niu', NULL, 'Niuean', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('nog', NULL, 'Nogai', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('non', NULL, 'Norse, Old', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('nai', NULL, 'North American Indian', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('sme', 'se', 'Northern Sami', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('nor', 'no', 'Norwegian', 'Norsk');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('nob', 'nb', 'Norwegian Bokmål', 'Norsk');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('nno', 'nn', 'Norwegian Nynorsk', 'Norsk');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('nub', NULL, 'Nubian languages', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('nym', NULL, 'Nyamwezi', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('nyn', NULL, 'Nyankole', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('nyo', NULL, 'Nyoro', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('nzi', NULL, 'Nzima', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('oji', 'oj', 'Ojibwa', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ori', 'or', 'Oriya', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('orm', 'om', 'Oromo', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('osa', NULL, 'Osage', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('oss', 'os', 'Ossetian; Ossetic', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('oto', NULL, 'Otomian languages', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('pal', NULL, 'Pahlavi', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('pau', NULL, 'Palauan', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('pli', 'pi', 'Pali', 'पालि');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('pam', NULL, 'Pampanga; Kapampangan', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('pag', NULL, 'Pangasinan', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('pap', NULL, 'Papiamento', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('paa', NULL, 'Papuan', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('per', 'fa', 'Persian', 'فارسی');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('phi', NULL, 'Philippine', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('phn', NULL, 'Phoenician', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('pon', NULL, 'Pohnpeian', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('pol', 'pl', 'Polish', 'Polski');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('por', 'pt', 'Portuguese', 'Português');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('pra', NULL, 'Prakrit languages', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('pan', 'pa', 'Punjabi; Panjabi', 'ਪੰਜਾਬੀ, پنجابی');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('pus', 'ps', 'Pushto', 'پښت');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('que', 'qu', 'Quechua', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('roh', 'rm', 'Raeto-Romance', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('raj', NULL, 'Rajasthani', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('rap', NULL, 'Rapanui', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('rar', NULL, 'Rarotongan', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('roa', NULL, 'Romance', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('rum', 'ro', 'Romanian', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('rom', NULL, 'Romany', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('run', 'rn', 'Rundi', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('rus', 'ru', 'Russian', 'Русский');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('sah', NULL, 'Sakha (Yakut)', 'Саха тыла');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('sal', NULL, 'Salishan languages', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('sam', NULL, 'Samaritan Aramaic', 'ארמית, ܐܪܡܝܐ');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('smi', NULL, 'Sami languages', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('smo', 'sm', 'Samoan', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('sad', NULL, 'Sandawe', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('sag', 'sg', 'Sango', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('san', 'sa', 'Sanskrit', 'संस्कृतम्');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('sat', NULL, 'Santali', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('srd', 'sc', 'Sardinian', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('sas', NULL, 'Sasak', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('sco', NULL, 'Scots', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('gla', 'gd', 'Scottish Gaelic; Gaelic', 'Gàidhlig');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('sel', NULL, 'Selkup', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('sem', NULL, 'Semitic', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('scc', 'sr', 'Serbian', 'српски');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('srr', NULL, 'Serer', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('shn', NULL, 'Shan', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('sna', 'sn', 'Shona', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('iii', 'ii', 'Sichuan Yi', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('scn', NULL, 'Sicilian', 'Sicilianu');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('sid', NULL, 'Sidamo', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('sgn', NULL, 'Sign languages', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('bla', NULL, 'Siksika', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('snd', 'sd', 'Sindhi', 'سنڌي، سندھی, सिन्धी');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('sin', 'si', 'Sinhalese; Sinhala', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('sit', NULL, 'Sino-Tibetan', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('sio', NULL, 'Siouan languages', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('sms', NULL, 'Skolt Sami', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('den', NULL, 'Slave (Athapascan)', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('sla', NULL, 'Slavic', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('slo', 'sk', 'Slovak', 'slovenčina');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('slv', 'sl', 'Slovenian', 'slovenščina');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('sog', NULL, 'Sogdian', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('som', 'so', 'Somali', 'af Soomaali');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('son', NULL, 'Songhai', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('snk', NULL, 'Soninke', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('wen', NULL, 'Sorbian languages', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('nso', NULL, 'Sotho, Northern; Pedi; Sepedi', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('sot', 'st', 'Sotho, Southern', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('sai', NULL, 'South American Indian', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('alt', NULL, 'Southern Altai', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('sma', NULL, 'Southern Sami', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('spa', 'es', 'Spanish; Castilian', 'español, castellano');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('suk', NULL, 'Sukuma', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('sux', NULL, 'Sumerian', 'eme-ĝir');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('sun', 'su', 'Sundanese', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('sus', NULL, 'Susu', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('swa', 'sw', 'Swahili', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ssw', 'ss', 'Swati', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('swe', 'sv', 'Swedish', 'Svenska');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('syr', NULL, 'Syriac', 'ܣܘܪܝܝܐ');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('tgl', 'tl', 'Tagalog', 'Tagalog');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('tah', 'ty', 'Tahitian', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('tai', NULL, 'Tai', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('tgk', 'tg', 'Tajik', 'тоҷикӣ, تاجیکی');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('tmh', NULL, 'Tamashek', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('tam', 'ta', 'Tamil', 'தமிழ');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('tat', 'tt', 'Tatar', 'татарча, tatarça, تاتارچا');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('tel', 'te', 'Telugu', 'తెలుగు');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ter', NULL, 'Tereno', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('tet', NULL, 'Tetum', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('tha', 'th', 'Thai', 'ภาษาไทย');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('tib', 'bo', 'Tibetan', 'བོད་ཡིག');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('tig', NULL, 'Tigre', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('tir', 'ti', 'Tigrinya', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('tem', NULL, 'Timne', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('tiv', NULL, 'Tiv', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('tli', NULL, 'Tlingit', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('tpi', NULL, 'Tok Pisin', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('tkl', NULL, 'Tokelau', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('tog', NULL, 'Tonga (Malawi)', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ton', 'to', 'Tongan', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('tsi', NULL, 'Tsimshian', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('tso', 'ts', 'Tsonga', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('tsn', 'tn', 'Tswana', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('tul', NULL, 'Tulu', 'ತುಳು');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('tum', NULL, 'Tumbuka', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('tup', NULL, 'Tupi languages', 'Nheengatu');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('tur', 'tr', 'Turkish', 'Türkçe');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('tuk', 'tk', 'Turkmen', 'Түркмен');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('tvl', NULL, 'Tuvalu', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('tyv', NULL, 'Tuvinian', 'Тыва дыл');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('twi', 'tw', 'Twi', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('udm', NULL, 'Udmurt', 'удмурт кыл');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('uga', NULL, 'Ugaritic', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('uig', 'ug', 'Uighur; Uyghur', 'ئۇيغۇرچ, Uyğurçe, 维吾尔语');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ukr', 'uk', 'Ukrainian', 'українська мова');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('umb', NULL, 'Umbundu', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('hsb', NULL, 'Upper Sorbian', 'hornjoserbsce');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('urd', 'ur', 'Urdu', 'اردو');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('uzb', 'uz', 'Uzbek', 'O''zbek, Ўзбек, أۇزبېك');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('vai', NULL, 'Vai', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ven', 've', 'Venda', 'Tshivenda');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('vie', 'vi', 'Vietnamese', 'Tiếng Việt');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('vol', 'vo', 'Volapük', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('vot', NULL, 'Votic', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('wak', NULL, 'Wakashan languages', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('wal', NULL, 'Walamo', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('wln', 'wa', 'Walloon', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('war', NULL, 'Waray', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('was', NULL, 'Washo', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('wel', 'cy', 'Welsh', 'Cymraeg');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('wol', 'wo', 'Wolof', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('wuu', NULL, 'Wu Chinese (Shanghainese)', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('xho', 'xh', 'Xhosa', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('yao', NULL, 'Yao', 'Chiyao');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('yap', NULL, 'Yapese', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('yid', 'yi', 'Yiddish', 'ייִדיש');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('yor', 'yo', 'Yoruba', 'Yorùbá');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('ypk', NULL, 'Yupik languages', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('znd', NULL, 'Zande', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('zap', NULL, 'Zapotec', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('zen', NULL, 'Zenaga', NULL);
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('zha', 'za', 'Zhuang; Chuang', 'Sawcuengh');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('zul', 'zu', 'Zulu', 'isiZulu');
insert into tablaidiomas (codigo, codigo2, descripcion, original) values ('zun', NULL, 'Zuni', 'Shiwi');